package com.seanghay.studio.gles.transition

object TransitionStore {

    fun simpleFadeTransition(): Transition = FadeTransition("fade", 1000L)

    fun getAllTransitions(): List<Transition> = listOf(
        FadeTransition("fade", 1000L),
        AngularTransition(),
        BounceTransition(),
        BowTieHorizontalTransition(),
        BowTieVerticalTransition(),
        BurnTransition(),
        ButterflyWaveScrawlerTransition(),
        CannabisleafTransition(),
        CircleCropTransition(),
        CircleTransition(),
        CircleopenTransition(),
        ColorphaseTransition(),
        ColourDistanceTransition(),
        CrazyParametricFunTransition(),
        CrossZoomTransition(),
        CrosshatchTransition(),
        CrosswarpTransition(),
        CubeTransition(),
        DirectionalTransition(),
        DirectionalwarpTransition(),
        DirectionalwipeTransition(),
        DoomScreenTransitionTransition(),
        DoorwayTransition(),
        DreamyTransition(),
        DreamyZoomTransition(),
        FadecolorTransition(),
        FadegrayscaleTransition(),
        FlyeyeTransition(),
        GlitchDisplaceTransition(),
        GlitchMemoriesTransition(),
        HeartTransition(),
        HexagonalizeTransition(),
        InvertedPageCurlTransition(),
        KaleidoscopeTransition(),
        LinearBlurTransition(),
        LuminanceMeltTransition(),
        MorphTransition(),
        MosaicTransition(),
        MultiplyBlendTransition(),
        PerlinTransition(),
        PinwheelTransition(),
        PolarFunctionTransition(),
        PolkaDotsCurtainTransition(),
        RadialTransition(),
        RippleTransition(),
        RotateScaleFadeTransition(),
        SimpleZoomTransition(),
        SqueezeTransition(),
        StereoViewerTransition(),
        SwapTransition(),
        SwirlTransition(),
        UndulatingBurnOutTransition(),
        WaterDropTransition(),
        WindTransition(),
        WindowblindsTransition(),
        WindowsliceTransition(),
        WipeDownTransition(),
        WipeLeftTransition(),
        WipeRightTransition(),
        WipeUpTransition(),
        ZoomInCirclesTransition()
    )
}